language: python
dist: trusty

python:
  - '3.6'
  - 'nightly'

sudo: false

install:
  - pip install -r requirements.txt
  - pip install pylint

script:
  - pylint mawabot

notifications:
  email:
    on_success: change
    on_failure: change
