language: python
dist: trusty

python:
  - '3.6'
  - 'nightly'

sudo: false

install:
  - pip install -r requirements.txt
  - pip install pylint

script:
  - pylint mawabot
  - pylint mawabot/cogs/general
  - pylint mawabot/cogs/guild
  - pylint mawabot/cogs/info
  - pylint mawabot/cogs/messages
  - pylint mawabot/cogs/programming
  - pylint mawabot/cogs/text

notifications:
  email:
    on_success: change
    on_failure: change
